//! Non-Rust file inventory.
//!
//! Enumerates every tracked file in the workspace via `git ls-files -z`,
//! classifies each as Rust source or non-Rust, and emits the result as
//! Markdown plus JSON under `target/policy/`.
//!
//! Future PRs (#204, #205) extend this with the checker and proposal
//! generator that consume the inventory.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};
use serde::Serialize;

const OUTPUT_DIR_REL: &str = "target/policy";
const MD_NAME: &str = "non-rust-inventory.md";
const JSON_NAME: &str = "non-rust-inventory.json";

/// Classification of a tracked file.
///
/// The current split is intentionally binary: `.rs` files are `RustSource`,
/// everything else is `NonRust`. The non-Rust set is what subsequent
/// file-policy checks reason about.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
enum Category {
    RustSource,
    NonRust,
}

#[derive(Debug, Serialize)]
struct InventorySummary {
    total: usize,
    rust_source: usize,
    non_rust: usize,
}

#[derive(Debug, Serialize)]
struct ExtensionBucket<'a> {
    extension: &'a str,
    count: usize,
}

#[derive(Debug, Serialize)]
struct Inventory<'a> {
    tool: &'static str,
    summary: InventorySummary,
    by_extension: Vec<ExtensionBucket<'a>>,
    non_rust_paths: Vec<String>,
    rust_source_paths: Vec<String>,
}

pub fn inventory() -> Result<()> {
    let workspace_root = workspace_root()?;
    let tracked = git_ls_files(&workspace_root)?;

    let mut rust_source: Vec<String> = Vec::new();
    let mut non_rust: Vec<String> = Vec::new();
    for path in &tracked {
        match classify(path) {
            Category::RustSource => rust_source.push(path.clone()),
            Category::NonRust => non_rust.push(path.clone()),
        }
    }

    let by_extension = extension_buckets(&non_rust);

    let inventory = Inventory {
        tool: "cargo xtask non-rust inventory",
        summary: InventorySummary {
            total: tracked.len(),
            rust_source: rust_source.len(),
            non_rust: non_rust.len(),
        },
        by_extension: by_extension
            .iter()
            .map(|(ext, count)| ExtensionBucket {
                extension: ext.as_str(),
                count: *count,
            })
            .collect(),
        non_rust_paths: non_rust.clone(),
        rust_source_paths: rust_source.clone(),
    };

    let out_dir = workspace_root.join(OUTPUT_DIR_REL);
    fs::create_dir_all(&out_dir)
        .with_context(|| format!("creating output directory {}", out_dir.display()))?;

    let json_path = out_dir.join(JSON_NAME);
    let json = serde_json::to_string_pretty(&inventory).context("serializing inventory as JSON")?;
    fs::write(&json_path, json).with_context(|| format!("writing {}", json_path.display()))?;

    let md_path = out_dir.join(MD_NAME);
    fs::write(&md_path, render_markdown(&inventory))
        .with_context(|| format!("writing {}", md_path.display()))?;

    println!(
        "wrote {} ({} total, {} Rust, {} non-Rust)",
        out_dir.display(),
        inventory.summary.total,
        inventory.summary.rust_source,
        inventory.summary.non_rust,
    );
    Ok(())
}

fn classify(path: &str) -> Category {
    if Path::new(path)
        .extension()
        .and_then(|s| s.to_str())
        .is_some_and(|ext| ext.eq_ignore_ascii_case("rs"))
    {
        Category::RustSource
    } else {
        Category::NonRust
    }
}

fn extension_buckets(paths: &[String]) -> Vec<(String, usize)> {
    let mut counts: BTreeMap<String, usize> = BTreeMap::new();
    for path in paths {
        let key = Path::new(path)
            .extension()
            .and_then(|s| s.to_str())
            .map(|s| format!(".{}", s.to_ascii_lowercase()))
            .unwrap_or_else(|| "(no extension)".to_string());
        *counts.entry(key).or_default() += 1;
    }
    let mut entries: Vec<_> = counts.into_iter().collect();
    entries.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(&b.0)));
    entries
}

fn render_markdown(inv: &Inventory<'_>) -> String {
    let mut out = String::new();
    out.push_str("# Non-Rust File Inventory\n\n");
    out.push_str("Generated by `cargo xtask non-rust inventory`.\n\n");
    out.push_str("## Summary\n\n");
    out.push_str(&format!("- Total tracked files: {}\n", inv.summary.total));
    out.push_str(&format!(
        "- Rust source (`*.rs`): {}\n",
        inv.summary.rust_source
    ));
    out.push_str(&format!("- Non-Rust: {}\n\n", inv.summary.non_rust));

    out.push_str("## Non-Rust files by extension\n\n");
    out.push_str("| Extension | Count |\n");
    out.push_str("|---|---:|\n");
    for bucket in &inv.by_extension {
        out.push_str(&format!("| `{}` | {} |\n", bucket.extension, bucket.count));
    }
    out.push('\n');

    out.push_str("## Non-Rust files\n\n");
    if inv.non_rust_paths.is_empty() {
        out.push_str("_(none)_\n");
    } else {
        for path in &inv.non_rust_paths {
            out.push_str(&format!("- `{}`\n", path));
        }
    }

    out
}

fn workspace_root() -> Result<PathBuf> {
    let manifest_dir = env_var("CARGO_MANIFEST_DIR")
        .context("CARGO_MANIFEST_DIR not set; run via `cargo xtask`")?;
    let xtask_dir = PathBuf::from(manifest_dir);
    let root = xtask_dir
        .parent()
        .with_context(|| format!("xtask manifest dir has no parent: {}", xtask_dir.display()))?
        .to_path_buf();
    Ok(root)
}

fn env_var(name: &str) -> Result<String> {
    std::env::var(name).with_context(|| format!("reading env var {name}"))
}

fn git_ls_files(workspace_root: &Path) -> Result<Vec<String>> {
    let output = Command::new("git")
        .arg("-C")
        .arg(workspace_root)
        .arg("ls-files")
        .arg("-z")
        .output()
        .context("running `git ls-files -z`")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!(
            "`git ls-files -z` exited {}: {}",
            output.status,
            stderr.trim()
        );
    }

    let entries: Vec<String> = output
        .stdout
        .split(|&b| b == 0)
        .filter(|s| !s.is_empty())
        .map(|bytes| String::from_utf8_lossy(bytes).into_owned())
        .collect();

    Ok(entries)
}
